apiVersion: v1
kind: ClusterRole
metadata:
  name: graphql-lb-reader
  namespace: graphql-lb
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "nodes"]
    verbs: ["get", "list", "watch"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: graphql-lb

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: graphql-lb-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: graphql-lb-reader
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: graphql-lb
